blocks:
    template:
        name: Fancy block name
        icon: bundles/ezsystemslandingpageblocktemplate/images/templateblock.svg
        available: true
        attributes:
            templateContent:
                name: Content
                type: text
                regex: /[^\s]/
                regexErrorMessage: 'No whitespaces allowed'
            test: string
        views:
            default:
                template: EzSystemsLandingPageBlockTemplateBundle::template.html.twig
                name: Basic Template Block view
