blocks:
    template:
        icon: bundles/ezsystemslandingpageblocktemplate/images/templateblock.svg
        attributes:
            templateContent:
                display_name: Content
                type: text
                validation:
                    regex: /[^\\s]/
                    message: 'Sample content'
        views:
            default:
                template: EzSystemsLandingPageBlockTemplateBundle::template.html.twig
                name: Basic Template Block view
