blocks:
    fancy:
        name: Fancy
        thumbnail: bundles/ezsystemslandingpageblocktemplate/images/templateblock.svg
        attributes:
            age:
                name: Age
                type: integer
                regex: /[0-9]+/
                regexErrorMessage: 'Provide a number'
            name: string
        views:
            default:
                template: EzSystemsLandingPageBlockTemplateBundle::fancy_block.html.twig
                name: Basic Template Block view
    more_fancy:
        initialize: true
        thumbnail: bundles/ezsystemslandingpageblocktemplate/images/templateblock.svg
        attributes:
            age: integer
            name: string
        views: EzSystemsLandingPageBlockTemplateBundle::more_fancy_block.html.twig
